name: Build GDExtension (Debug)
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - { platform: linux, arch: x86_32, os: ubuntu-22.04 }
          - { platform: linux, arch: x86_64, os: ubuntu-22.04 }
          - { platform: linux, arch: arm32, os: ubuntu-22.04-arm }
          - { platform: linux, arch: arm64, os: ubuntu-22.04-arm }
          - { platform: windows, arch: x86_32, os: windows-latest }
          - { platform: windows, arch: x86_64, os: windows-latest }
          - { platform: windows, arch: arm64, os: windows-latest }
          - { platform: macos, arch: universal, os: macos-latest }
          - { platform: android, arch: x86_64, os: ubuntu-22.04 }
          - { platform: android, arch: arm32, os: ubuntu-22.04 }
          - { platform: android, arch: arm64, os: ubuntu-22.04 }
          - { platform: ios, arch: arm64, os: macos-latest }
          - { platform: web, arch: wasm32, os: ubuntu-22.04, threads: enabled }
          - { platform: web, arch: wasm32, os: ubuntu-22.04, threads: disabled }
        float-precision: [single, double]
        target-type: [template_debug]

    runs-on: ${{ matrix.target.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install multilib support
        if: ${{ matrix.target.platform == 'linux' && matrix.target.arch == 'x86_32' }}
        run: |
          sudo apt-get update && sudo apt-get install -y gcc-multilib g++-multilib

      - name: Setup godot-cpp
        uses: ./godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.target.platform }}
          em-version: 3.1.62

      - name: Restore .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-restore
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}

      - name: Build godot-cpp for macOS/iOS
        if: ${{ matrix.target.platform == 'macos' || matrix.target.platform == 'ios' }}
        run: |
          cd godot-cpp
          if [ "${{ matrix.target.platform }}" = "macos" ]; then
            scons platform=${{ matrix.target.platform }} arch=x86_64 target=${{ matrix.target-type }} precision=${{ matrix.float-precision }} threads=${{ matrix.target.threads == 'enabled' && 'true' || 'false' }} use_lto=false
            scons platform=${{ matrix.target.platform }} arch=arm64 target=${{ matrix.target-type }} precision=${{ matrix.float-precision }} threads=${{ matrix.target.threads == 'enabled' && 'true' || 'false' }} use_lto=false
            mkdir -p bin/libgodot-cpp.macos.${{ matrix.target-type }}.${{ matrix.float-precision }}.framework
            lipo -create bin/libgodot-cpp.macos.${{ matrix.target-type }}.x86_64.a bin/libgodot-cpp.macos.${{ matrix.target-type }}.arm64.a -output bin/libgodot-cpp.macos.${{ matrix.target-type }}.${{ matrix.float-precision }}.framework/libgodot-cpp
            cp -r misc/macos/Info.plist bin/libgodot-cpp.macos.${{ matrix.target-type }}.${{ matrix.float-precision }}.framework/Info.plist
            mv bin/libgodot-cpp.macos.${{ matrix.target-type }}.${{ matrix.float-precision }}.framework ../bin/macos/
          else
            scons platform=${{ matrix.target.platform }} arch=arm64 target=${{ matrix.target-type }} precision=${{ matrix.float-precision }} threads=${{ matrix.target.threads == 'enabled' && 'true' || 'false' }}
            xcodebuild -create-xcframework \
              -library bin/libgodot-cpp.ios.${{ matrix.target-type }}.arm64.a \
              -output bin/libgodot-cpp.ios.${{ matrix.target-type }}.${{ matrix.float-precision }}.xcframework
            mv bin/libgodot-cpp.ios.${{ matrix.target-type }}.${{ matrix.float-precision }}.xcframework ../bin/ios/
          fi

      - name: Build GDExtension
        shell: sh
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons-cache/
        run: |
          scons target=${{ matrix.target-type }} platform=${{ matrix.target.platform }} arch=${{ matrix.target.arch }} precision=${{ matrix.float-precision }} threads=${{ matrix.target.threads == 'enabled' && 'true' || 'false' }} use_lto=false

      - name: Save .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-save
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}

      - name: Windows - Delete compilation files
        if: ${{ matrix.target.platform == 'windows' }}
        shell: pwsh
        run: |
          Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force

      - name: Run Tests (Linux, Debug)
        if: ${{ matrix.target.platform == 'linux' && matrix.target.arch == 'x86_64' && matrix.target-type == 'template_debug' }}
        run: |
          wget "https://github.com/godotengine/godot-builds/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip" -O Godot.zip
          unzip -a Godot.zip
          chmod +x Godot_v4.3-stable_linux.x86_64
          cd test_project
          ../Godot_v4.3-stable_linux.x86_64 --headless --import
          ../Godot_v4.3-stable_linux.x86_64 --headless --script run-tests.gd

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-plus-plus-${{ matrix.target.platform }}-${{ matrix.target.arch }}-${{ matrix.float-precision }}-${{ matrix.target-type }}${{ matrix.target.threads != '' && format('-{0}', matrix.target.threads) || '' }}
          path: |
            ${{ github.workspace }}/bin/**
            ${{ github.workspace }}/test_project/**
            !${{ github.workspace }}/bin/**/libgodot-cpp*.a

  merge:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: godot-plus-plus-debug
          pattern: godot-plus-plus-*
          delete-merged: true